-- Table for Social Media Queue
create table if not exists social_posts (
  id bigint generated by default as identity primary key,
  content text, 
  platforms text[], -- Array of strings: ['facebook', 'instagram']
  media_urls text[], -- Array of image URLs
  status text default 'scheduling', -- 'scheduling', 'sent', 'failed'
  ayrshare_id text, -- ID returned by Ayrshare
  response_data jsonb, -- Full response from Ayrshare
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- Enable RLS
alter table social_posts enable row level security;

-- Policies
create policy "Authenticated users can insert social posts"
on social_posts for insert
to authenticated
with check (true);

create policy "Authenticated users can view social posts"
on social_posts for select
to authenticated
using (true);

create policy "Service role full access"
on social_posts
to service_role
using (true)
with check (true);

-- Enable Realtime
alter publication supabase_realtime add table social_posts;
