-- Run this in your Supabase SQL Editor

create table if not exists whatsapp_outbox (
  id bigint generated by default as identity primary key,
  phone text not null,
  message text, -- Can be template name or custom text (if flexible)
  status text default 'scheduling', -- 'scheduling', 'sent', 'failed'
  response_data jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS (Optional, but good practice)
alter table whatsapp_outbox enable row level security;

-- Policy: Allow authenticated users (Operators/Marketers) to insert messages
create policy "Authenticated users can insert messages"
on whatsapp_outbox for insert
to authenticated
with check (true);

-- Policy: Allow users to view their own messages (if you link to user_id, 
-- currently table has no user_id, so public read might be needed or restricted to service role)
-- For now, allow authenticated to select to see status
create policy "Authenticated users can view messages"
on whatsapp_outbox for select
to authenticated
using (true);
