-- Add facebook_psid to clients table
ALTER TABLE clients
ADD COLUMN IF NOT EXISTS facebook_psid text;

-- Create messenger_outbox table
CREATE TABLE IF NOT EXISTS messenger_outbox (
  id bigint generated by default as identity primary key,
  organization_id text not null,
  psid text not null,
  message text not null, -- Plain text message for now
  status text default 'scheduling', -- 'scheduling', 'sent', 'failed'
  media_urls text[] default '{}',
  response_data jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Note: In older PostgreSQL, IF NOT EXISTS is not supported for ADD COLUMN, but on Supabase's Postgres 15+ it is.

-- Enable RLS
ALTER TABLE messenger_outbox ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Authenticated users can insert messenger tasks"
ON messenger_outbox FOR INSERT
TO authenticated
WITH CHECK (true);

CREATE POLICY "Authenticated users can view messenger tasks"
ON messenger_outbox FOR SELECT
TO authenticated
USING (true);
